spring:
  application:
    name: api-productos
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: Javi
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: api-productos